### ISSUE TITLE
Inquiry on Code Release Date

### ISSUE THREAD

**Issue by Corazon-XYC** [LIANGKE23/SIGIR23-RPC#1]
Dear Author,

I hope this message finds you well. I'm interested in your paper. Could you please let me know when the associated code will be released?

Thank you.

**Comment by LIANGKE23** [comment]
Thanks for your interest. We are extending the journal based on it. After finishing it, we will release it.
Similar idea are also used in other TKGR models, such as HGLS. More models can be found in https://github.com/LIANGKE23/Awesome-Knowledge-Graph-Reasoning.
